### ISSUE TITLE
About x_position in the code

### ISSUE THREAD

**Issue by leuchine** [JiaxuanYou/P-GNN#1]
Hi Jiaxuan:

Thanks for sharing the code. It is a great project!

I have a question about using x_position as the output. Each dimension of x_position corresponds to an anchor set. As the anchor sets are re-sampled at each epoch, x_position is permuted and the correspondence to anchor sets changed. This will introduce instability to the algorithm? Thanks!

Best Regards,
Qi

**Comment by JiaxuanYou** [comment]
Hi, thanks for the question.
What you've mentioned is correct. That's why I do not feed x_position into next layer but x_structure. All the task consider here are pairwise prediction tasks, and we use dot product to make prediction, which is order invariant.
