### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by jia1995** [JiaxuanYou/P-GNN#4]
hello Jiaxuan：
       when i running follow code in terminal：
           python main.py --model PGNN --num_layers 2 --dataset grid
encountered the following problem.
![2019-07-19 15-52-36屏幕截图](https://user-images.githubusercontent.com/16118184/61518968-5fe3c380-aa3d-11e9-84e6-0d64aeef1ec7.png)

**Comment by mtli77** [comment]
> hello Jiaxuan：
> when i running follow code in terminal：
> python main.py --model PGNN --num_layers 2 --dataset grid
> encountered the following problem.
> ![2019-07-19 15-52-36屏幕截图](https://user-images.githubusercontent.com/16118184/61518968-5fe3c380-aa3d-11e9-84e6-0d64aeef1ec7.png)

Hi, I also face this error, could you tell me how did you solve this ?
