### ISSUE TITLE
how to get it running without Nvidia GPU

### ISSUE THREAD

**Issue by JoyXu123** [JiaxuanYou/P-GNN#9]
Hi Jiaxuan,

Is there a way to get the program running even without GPU?
![Screenshot from 2019-10-16 14-54-02](https://user-images.githubusercontent.com/26353946/66949594-cec4be80-f024-11e9-9c85-479d0f65b1cb.png)

**Comment by zhiqiangzhongddu** [comment]
just switch the parameter (GPU=True to False) of args.py file
